# Each weblogic environment should be defined in the following format:
# [environment_id_1]
# environment_name=(should be unique, short and can be used to specify which environment to use when running the wlst scripts)
# admin_server_url=http://admin_server_host:admin_server_port
# user_name=username
# [environment_id_2]
# environment_name=(should be unique, short and can be used to specify which environment to use when running the wlst scripts)
# admin_server_url=http://admin_server_host:admin_server_port
# user_name=username
[WLS12_DEV]
environment_name=Weblogic 12c Dev 1
admin_server_url=t3://10.0.0.170:7001
user_name=weblogic
[WLS15_DEV]
environment_name=Weblogic 15.1.1 Dev 2
admin_server_url=t3://10.0.0.193:7001
user_name=weblogic